version: '3.2'

services:

  web:
    container_name: backend-service
    build:
      context: ../../project-template-cards-clc-backend-master/project-template-cards-clc-backend-master/backend-service
      dockerfile: Dockerfile
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/backend-service
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: root
    depends_on:
    - db
    ports:
    - 8080:8080
    links:
    - db
    networks:
    - app

  db:
    container_name: backend-service-database
    build: ../../project-template-cards-clc-backend-master/project-template-cards-clc-backend-master/backend-service/docker/db
    restart: always
    environment:
      POSTGRES_DB: backend-service
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
    - 5432:5432
    volumes:
    - type: volume
      source: psql_data
      target: /var/lib/postgresql/data
    networks:
    - app

  adminer:
    build: ../../project-template-cards-clc-backend-master/project-template-cards-clc-backend-master/backend-service/docker/adminer
    restart: always
    ports:
    - 6080:8080
    networks:
    - app

volumes:
  psql_data:
networks:
  app:
